src/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as rest_framework_views

from . import api

app_name = 'api'

router = DefaultRouter()

urlpatterns = [

    # Singular Paths
    path('', include(router.urls), name='index'),
    path('get/auth/token/', rest_framework_views.obtain_auth_token, name='get-auth-token'),

    # Task Paths
    path('user/<int:id>/tasks/', api.UserTaskListAPIHandler.as_view(), name='tasks-by-user'),
    path('task/<int:id>/delete/', api.TaskDeleteAPIHandler.as_view(), name='task-delete'),
    path('task/create/', api.TaskCreateAPIHandler.as_view(), name='task-create'),

]

src/novastone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('todo.urls', namespace='todo')),
]

src/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [

    # Singular Paths
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Task URLS
    path('', views.TaskListView.as_view(), name='task-list'),
    path('tasks/create/', views.TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task-delete'),
    path('tasks/<int:pk>/update/', views.TaskUpdateView.as_view(), name='task-update'),

    # API
    path('testing/', views.APITestView.as_view(), name='api-test'),

]

src/todo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Task(models.Model):
    """
    Stores a single task which has relationships with :model:'auth.User' model.
    """
    created = models.DateTimeField(auto_now_add=True, editable=False)

    # Fields
    name = models.CharField(max_length=25)
    description = models.TextField(verbose_name='Description')
    status = models.BooleanField(default=False)

    # Relational Fields
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_set')
    done_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='task_done_by_set', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_status(self):
        """
        Constructs string based of status of task.
        :return: string
        """
        return 'Complete' if self.status else 'Incomplete'


@receiver(pre_save, sender=Task)
def update_done_by(sender, instance, **kwargs):
    if not instance.status and instance.done_by:
        instance.done_by = None

src/todo/views.py
from braces.views import LoginRequiredMixin, UserPassesTestMixin, AnonymousRequiredMixin
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import (CreateView, DeleteView, FormView,
                                  ListView, RedirectView, UpdateView, TemplateView)

from .models import Task


class LoginView(AnonymousRequiredMixin, FormView):
    """
    Handles authentication of User. Can only be accessed by user's who
    have not logged in.
    """
    template_name = 'todo/inc/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy(settings.AUTHENTICATED_REDIRECT_URL)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        return self.success_url


class LogoutView(RedirectView):
    """
    Simple view to handle User logout.
    """
    url = reverse_lazy(settings.AUTHENTICATED_REDIRECT_URL)

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class TaskListView(LoginRequiredMixin, ListView):
    """
    Lists all the tasks and can only be accessed by logging in.
    """
    template_name = 'todo/inc/index.html'
    model = Task
    login_url = reverse_lazy(settings.LOGIN_URL)
    paginate_by = 5
    ordering = '-created'


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Displays Task creation form which can only access by logged in user
    and displays success message on creation.
    """
    model = Task
    template_name = 'todo/inc/task_create.html'
    login_url = reverse_lazy(settings.LOGIN_URL)
    fields = ('name', 'description')
    success_url = reverse_lazy('todo:task-list', False)
    success_message = 'Successfully created task!'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Allows Task deletion which can only be done by the author of the task.

    Implications:
        User has to be logged in.
    """
    template_name = 'todo/inc/task_confirm_delete.html'
    model = Task
    success_url = reverse_lazy('todo:task-list')
    login_url = reverse_lazy(settings.LOGIN_URL)
    redirect_unauthenticated_users = reverse_lazy('todo:task-list')

    def test_func(self, user):
        return self.get_object().user == user

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Successfully deleted: %s!' % self.get_object().name)
        return super().delete(request, *args, **kwargs)


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    """
    Allows the author to update a task.

    Implications:
        User has to be logged in.
    """
    template_name = 'todo/inc/task_update.html'
    model = Task
    raise_exception = True
    fields = ('name', 'description', 'status',)
    success_url = reverse_lazy('todo:task-list')
    success_message = 'Successfully updated task!'
    redirect_unauthenticated_users = reverse_lazy('todo:task-list')

    def test_func(self, user):
        return self.get_object().user == user


class APITestView(TemplateView):
    template_name = 'todo/inc/api.html'

src/todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <title>TODO - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'todo/css/style.css' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"
            integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'todo/js/cookie-jquery/jquery.cookie.js' %}"></script>

</head>

<body>
<div class="header sticky">
    <div class="container">
        <div class="logo">
            <a href="{% url 'todo:task-list' %}">Novastone TODO</a>
        </div>
        <div class="navigation">
            {% if user.is_authenticated %}
                <span class="badge badge-primary" style="margin-right: 20px;"><b>{{ user.get_full_name }}</b></span>
                <a title="Logout" href="{% url 'todo:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
            {% endif %}
        </div>
    </div>
</div>
<div class="container">
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %}class="message {{ message.tags }}"{% endif %}>{{ message|safe }}</li>
        {% endfor %}
    </ul>
    {% block content %}
    {% endblock %}
</div>

{% block scripts %}
{% endblock %}

</body>
</html>

src/todo/templates/todo/inc/api.html
{% extends 'todo/base.html' %}

{% load static %}

{% block head %}
{% endblock %}

{% block title %}
    Index
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9 border-right-15">
            <h4>Test API Calls</h4>
            <div class="tasks">
                <div class="task">
                    <div class="name">Get List of Tasks</div>
                    <div class="text" id="get_data">
                    </div>
                    <div class="">
                        <button class="btn btn-primary" id="get_button">GET Tasks</button>
                    </div>
                </div>
                <div class="task">
                    <div class="name">Create a Task</div>
                    <div class="text" id="post_data">
                    </div>
                    <div class="">
                        <button class="btn btn-primary" id="post_button">POST Task</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        let token = '45e33ce10f5df28c12e6dd9f3bbd89bcd26b21bd';
        $.ajaxSetup({
            headers:{
              'Authorization': "Token " + token
            }
        });

        // jQuery GET
        $('#get_button').click(function () {
            $.get("/api/user/2/tasks/", function (data) {
                $('#get_data').hide().html(JSON.stringify(data)).fadeIn();
            })
        });

        let post_data = {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            "name":"Send New Annoucements",
            "description": "Send out wedding announcements to the local news papers.",
            "status": false,
            "user": 1
        };

        $('#post_button').click(function () {
            $.post("/api/task/create/", post_data, function (data) {
                $('#post_data').hide().html(JSON.stringify(data)).fadeIn();
            });
        });
    </script>
{% endblock %}

src/todo/templates/todo/inc/index.html
{% extends 'todo/base.html' %}

{% load static %}

{% block head %}
{% endblock %}

{% block title %}
    Index
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9 border-right-15">
            <h4>All Tasks</h4>
            {% include 'todo/inc/pagination.html' %}
            <div class="tasks">
                {% for task in object_list %}
                    <div style="border: 1px solid #EEE;
                            background: {% if task.user == user %}rgba(219, 246, 251, 0.3) !important;{% endif %}"
                         class="task {% if task.status %}success{% endif %}" id="task{{ task.id }}">

                        <span class="badge
                                {% if task.user == user %}badge-primary{% else %}badge-white{% endif %}" title="Author">
                            {{ task.user.get_full_name }}
                        </span>
                        <span class="name">
                            {{ task.name }}
                        </span>
                        <span id="task-status-{{ task.id }}"
                              class="badge
                              {% if not task.status %}hidden{% endif %}
                              badge-success">
                            <i class="fas fa-check"></i> {{ task.done_by.get_full_name }}
                        </span>
                        <div class="text">
                            {{ task.description }}
                        </div>
                        <div class="attributes">
                            <div class="row">
                                <div class="col-md-12">
                                    {% if task.user == user %}
                                        <a href="{% url 'todo:task-update' task.pk %}">
                                            <button onclick="" class="btn btn-white">Edit</button>
                                        </a>
                                    {% endif %}
                                    {% if not task.status %}
                                        <button onclick="markDone(this);"
                                                href=""
                                                class="btn btn-white">
                                            Mark Done
                                        </button>
                                    {% endif %}
                                    {% if task.user == user %}
                                        <a href="{% url 'todo:task-delete' task.pk %}">
                                            <button class="btn btn-white">Delete</button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="" style="color: indianred;">No tasks. <a href="{% url 'todo:task-create' %}">Click here
                        to add
                        one</a>
                        .
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            {% include 'todo/inc/sidebar.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        let csrftoken = '{{ csrf_token }}';

        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function markDone(el) {
            let link = $(el).attr('href');
            $.ajax({
                type: 'PATCH',
                url: link,
                data: {
                    'status': true,
                    'done_by': {{ user.id }},
                },
                success: function (data) {
                    $('#task' + data.id).addClass('success');
                    $(el).remove();
                    $('#task-status-' + data.id)
                        .removeClass('hidden')
                },
                error: function (xhr, textStatus, error) {
                    console.log(xhr.statusText);
                    console.log(textStatus);
                    console.log(error)
                }
            });
        }

        let hidden = false;

        function hideCompletedTasks() {
            $('.task').each(function () {
                if ($(this).hasClass('success')) {
                    $(this).slideToggle();
                }
            });
            hidden = !hidden;
            let action = $('#hideCompletedTasks');
            if (hidden) {
                action.html('<i class="small-icon fas fa-eye"></i> Show Completed Tasks');
            } else {
                action.html('<i class="small-icon fas fa-eye-slash"></i> Hide Completed Tasks');
            }
        }

    </script>
{% endblock %}

src/todo/templates/todo/inc/login.html
{% extends 'todo/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 page">
            <h5>Login into access your TODO items.</h5>
            <hr/>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit">Login</button>
                </p>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

src/todo/templates/todo/inc/pagination.html
{% if is_paginated %}
    <nav style="margin-top: 20px;">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span>Previous</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled page-item">
                    <a href="#" class="page-link">
                        <span>Previous</span>
                    </a>
                </li>
            {% endif %}

            {% for page in paginator.page_range %}
                <li {% if page == page_obj.number %}class="active page-item"{% endif %}>
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span>Next</span>
                    </a>
                </li>
            {% else %}
                <li {% if not page_obj.has_next %}class="disabled page-item"{% endif %}>
                    <a class="page-link" href="#">
                        <span>Next</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

src/todo/templates/todo/inc/sidebar.html
<h4>Actions</h4>
<div class="actions">
    <a href="{% url 'todo:task-create' %}"><i class="small-icon fa fa-plus"></i> New Task</a>
    <span id="hideCompletedTasks" onclick="hideCompletedTasks();"><i class="small-icon fas
                   fa-eye-slash"></i> Hide Completed
                       Tasks</span>
</div>

src/todo/templates/todo/inc/task_confirm_delete.html
{% extends 'todo/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block title %}
    Task Create
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9 border-right-15">
            <h4 style="margin-bottom: 20px;">Deleting: {{ object.name }}</h4>
            <div class="page">
                <div class="" style="margin-bottom: 20px;">
                    <i>
                        {{ object.text }}
                    </i>
                </div>
                Are you sure you wish to delete the above <b>Task</b>?
                <br/>
                <br/>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger"><i class="fas fa-times"></i> Delete</button>
                </form>
            </div>
        </div>
        <div class="col-md-3">
            {% include 'todo/inc/sidebar.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

src/todo/templates/todo/inc/task_create.html
{% extends 'todo/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block title %}
    Task Create
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9 border-right-15">
            <h4 style="margin-bottom: 20px;">Add Task</h4>
            <div class="page">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Add</button>
                </form>
            </div>
        </div>
        <div class="col-md-3">
            {% include 'todo/inc/sidebar.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

src/todo/templates/todo/inc/task_update.html
{% extends 'todo/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock %}

{% block title %}
    Task Create
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9 border-right-15">
            <h4 style="margin-bottom: 20px;">Updating: {{ object.name }}</h4>
            <div class="page">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Update</button>
                </form>
            </div>
        </div>
        <div class="col-md-3">
            {% include 'todo/inc/sidebar.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}